services:
  notifications-db:
    image: postgres:15
    env_file:
      - .env.docker
    ports:
      - "5433:5432"
    volumes:
      - notifications-db:/var/lib/postgresql/data

    rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      env_file:
        - .env.docker

volumes:
    notifications-db:
